### ISSUE TITLE
Need previous version cleanup upon reinstall

### ISSUE THREAD

**Issue by hunterbarber** [CODES-group/opyrability#12]
Managed to install multiple versions somehow
```
opyrability         1.4.7
opyrability         1.4.9
opyrability         1.4.9
```

**Comment by hunterbarber** [comment]
Actually thinking this may be a result of combining conda and pip installs. I see opyrability and other packages get installed multiple times without clean up.

**Comment by victoraalves** [comment]
As we discussed in person, this is a problem when trying to install via setup.py which is deprecated and not recommended. Via pip things work well though :)

for local development `pip install -e .` with the terminal pointed at the project's root folder should yield the desired and expected results including the removal/cleanup of previous versions. Pip now uses `pyproject.toml` following [PEP 621](https://peps.python.org/pep-0621/).

I will close this one.
