### ISSUE TITLE
Suggestion -NSGA-II 

### ISSUE THREAD

**Issue by mustafaalsalmi1999** [CODES-group/opyrability#4]
NSGA-II (Non-dominated Sorting Genetic Algorithm II) can be effectively combined with process operability analysis to optimize the design and control of chemical processes by Including the operability set and its defining criteria (achievable inputs/outputs, desired operating regions, disturbances) as constraints in the NSGA-II optimization. NSGA-II will generate a set of Pareto optimal solutions that represent different trade-offs between design and operability objectives at specific variables. I believe that combining NSGA-II with process operability analysis, you can design and control chemical processes that are not only optimal in terms of desired objectives but also robust and operable under practical conditions. This integrated approach helps to avoid the pitfalls of sequential design and control and leads to more sustainable and efficient chemical production.

**Comment by victoraalves** [comment]
@mustafaalsalmi1999 Thank you for this interesting suggestion! I will certainly take this into consideration in future releases of the tool!
