### ISSUE TITLE
numpy fails to install with `pip install opyrability` when using python>3.10

### ISSUE THREAD

**Issue by hunterbarber** [CODES-group/opyrability#5]
`pip install opyrability` fails when environment is using newer than python 3.10 due to a failure with numpy

**Comment by victoraalves** [comment]
That's an important issue that is going on with several python packages as discussed in https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean

It is a bug related to the `setuptools` python package for Python >= 3.10.

A solution before attempting installing opyrability is running the following command:

`python -m pip install --upgrade setuptools`

I will leave this issue open for a while so people can easily see it if the come across this bug. Nothing we can do on our end, unfortunately

**Comment by victoraalves** [comment]
Looks like I fixed this on https://github.com/CODES-group/opyrability/commit/b1f619b249d4ea35f6b1874285f109b9f1e333b5 

Can you please try the following:

On Anaconda Prompt:

`conda create --name opy147`

`conda activate opy147`

`conda install -c conda-forge cyipopt`

Then, from the environment `opy147`

`python`

`import opyrability`

It should work. Cyipopt takes a while to be installed.

**Comment by hunterbarber** [comment]
Confirmed working on Python 3.11

**Comment by victoraalves** [comment]
closing them
