### ISSUE TITLE
Error with Polytrope Package

### ISSUE THREAD

**Issue by dhuynh10** [CODES-group/opyrability#7]
Hello, 

When I try to run the jupyter notebook for the shower example, I get the following error. I'm not sure why this is or what to do about it. Any help would be greatly appreciated! Specifically, this is from operability_index_shower.ipynb and from the following line of code: 

AOS_region  =  multimodel_rep(model, AIS_bounds, AIS_resolution)

Thanks!

See below for the error. 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[9], line 1
----> 1 AOS_region  =  multimodel_rep(model, AIS_bounds, AIS_resolution)

File ~\Anaconda3\envs\opyr2\lib\site-packages\opyrability.py:205, in multimodel_rep(model, bounds, resolution, polytopic_trace, perspective, plot, EDS_bound, EDS_resolution)
    202 AS_coords = np.concatenate(Vertices_list, axis=0)
    203 for i in range(len(mapped_region)):
--> 205     polyplot = _get_patch(mapped_region[i], linestyle="solid",
    206                         edgecolor=EDGES_COLORS, linewidth=EDGES_WIDTH,
    207                         facecolor=AS_COLOR)
    208     ax.add_patch(polyplot)
    211 lower_xaxis = mapped_region.bounding_box[0][0]

File ~\Anaconda3\envs\opyr2\lib\site-packages\polytope\polytope.py:2319, in _get_patch(poly1, **kwargs)
   2317 ind = np.argsort(angle)
   2318 # create patch
-> 2319 patch = mpl.patches.Polygon(V[ind, :], True, **kwargs)
   2320 patch.set_zorder(0)
   2321 return patch

TypeError: __init__() takes 2 positional arguments but 3 were given

**Comment by victoraalves** [comment]
The example runs fine for me when using opyrability 1.4.5 and its dependencies. From my local machine:
![image](https://github.com/CODES-group/opyrability/assets/50674829/6f2079b1-0968-46da-9389-c09559326c10)

This seems to be a matplotlib issue perhaps. Could you tell me which are your package versions for:

> Numpy 
> Scipy 
> Polytope 
> matplotlib 
> tqdm 
> CVXOPT 
> cyipopt
> JAX

**Comment by dhuynh10** [comment]
Thanks for the quick reply!!

Numpy == 1.26.4
Scipy == 1.12.0
Polytope == 0.2.4 
matplotlib == 3.8.3
tqdm == 4.66.2
CVXOPT == 1.3.2
cyipopt == 1.3.0
JAX == 0.4.23

**Comment by victoraalves** [comment]
> Thanks for the quick reply!!
> 
> Numpy == 1.26.4 Scipy == 1.12.0 Polytope == 0.2.4 matplotlib == 3.8.3 tqdm == 4.66.2 CVXOPT == 1.3.2 cyipopt == 1.3.0 JAX == 0.4.23

The problem is matplotlib v.3.8.3. The function Polygon seems to be have been reworked and hence, the polytope package needs to be updated to work for this new version. I was able to reproduce your error:
![error_matplotlib](https://github.com/CODES-group/opyrability/assets/50674829/ba0d2792-fa49-48bf-8c31-d85d305ad90f)


If you uninstall matplotlib 3.8.3 and install 3.7.3 for example via:

`pip install matplotlib==3.7.3 --user`

Then everything should run as expected.

I hope this helps!

**Comment by victoraalves** [comment]
@dhuynh10 let me know if it worked. It should be, but please confirm.

**Comment by dhuynh10** [comment]
@victoraalves Yes! It worked. Thank you. 

I have another error when I try to run the inverse_map_shower.ipynb file. I'm not sure if that's related or not. I can open another ticket if that's better. Thanks!!

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[3], line 12
      8 DOSresolution = [10, 10]
     11 t = time.time()
---> 12 fDIS, fDOS, message = nlp_based_approach(DOS_bound, 
     13                                           DOSresolution, 
     14                                           shower2x2, 
     15                                           u0, 
     16                                           lb,
     17                                           ub, 
     18                                           method='ipopt', 
     19                                           plot=True, 
     20                                           ad=False,
     21                                           warmstart=False)
     24 elapsed = time.time() - t

File ~/anaconda3/envs/opyr/lib/python3.9/site-packages/opyrability.py:800, in nlp_based_approach(model, DOS_bounds, DOS_resolution, u0, lb, ub, constr, method, plot, ad, warmstart)
    797     pass
    799 dimDOS = DOS_bounds.shape[0]
--> 800 DOSPts = create_grid(DOS_bounds, DOS_resolution)
    801 DOSPts = DOSPts.reshape(-1, dimDOS)
    802 u00    = u0

File ~/anaconda3/envs/opyr/lib/python3.9/site-packages/opyrability.py:1158, in create_grid(region_bounds, region_resolution)
   1156 # Create discretized region based on bounds and resolution information.
   1157 for i in range(nInput):
-> 1158     Input_u.append(list(np.linspace(region_bounds[i, 0],
   1159                                     region_bounds[i, 1],
   1160                                     region_resolution[i])))
   1162 # Create slack variables for preallocation purposes.
   1163 region_grid = np.zeros(region_resolution + [nInput])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by victoraalves** [comment]
@dhuynh10 Hey I'm glad it worked! Can you please send me a screenshot of this second error? Thanks.

**Comment by dhuynh10** [comment]
![image](https://github.com/CODES-group/opyrability/assets/161379005/fdd938f7-fec1-4097-ab4e-968ed9bd7bf9)

**Comment by victoraalves** [comment]
@dhuynh10 your function call for `nlp_based_approach` is wrong. Please check the documentation:

https://codes-group.github.io/opyrability/api.html#inverse-mapping-aos-dos-to-ais-dis

The first argument is the function handle for the process model (in your example, shower2x2).

Please read the documentation carefully so you can take full advantage of opyrability :)

**Comment by victoraalves** [comment]
Edit: @dhuynh10  This is my fault, the file you are pointing out corresponds to an old version of the shower problem inverse mapping that had this sequence of arguments. I apologize for the confusion. Please, refer to the updated version of this tutorial, at:

https://codes-group.github.io/opyrability/examples_gallery/operability_index_shower.html

Thanks for pointing that out, it is greatly appreciated!

**Comment by victoraalves** [comment]
@dhuynh10 the file you mentioned has been updated accordingly as well. Here's the link. https://github.com/CODES-group/opyrability/blob/main/docs/inverse_map_shower.ipynb

**Comment by dhuynh10** [comment]
Thank you! Everything seems to be working now. Greatly appreciated :)

**Comment by victoraalves** [comment]
I'm glad it works! :)
